export function answersFile() {
  var answers = []
  //hiragana
  answers.push(
  {kanji:"あ", reading: "", meanings:["a"], categories: ["hiragana"]},   
  {kanji:"い", reading: "", meanings:["i"], categories: ["hiragana"]},   
  {kanji:"う", reading: "", meanings:["u"], categories: ["hiragana"]},   
  {kanji:"え", reading: "", meanings:["e"], categories: ["hiragana"]},   
  {kanji:"お", reading: "", meanings:["o"], categories: ["hiragana"]},
  {kanji:"か", reading: "", meanings:["ka"], categories: ["hiragana"]},   
  {kanji:"き", reading: "", meanings:["ki"], categories: ["hiragana"]},   
  {kanji:"く", reading: "", meanings:["ku"], categories: ["hiragana"]},   
  {kanji:"け", reading: "", meanings:["ke"], categories: ["hiragana"]},   
  {kanji:"こ", reading: "", meanings:["ko"], categories: ["hiragana"]},
  {kanji:"が", reading: "", meanings:["ga"], categories: ["hiragana"]},
  {kanji:"ぎ", reading: "", meanings:["gi"], categories: ["hiragana"]},
  {kanji:"ぐ", reading: "", meanings:["gu"], categories: ["hiragana"]},
  {kanji:"げ", reading: "", meanings:["ge"], categories: ["hiragana"]},
  {kanji:"ご", reading: "", meanings:["go"], categories: ["hiragana"]},
  {kanji:"さ", reading: "", meanings:["sa"], categories: ["hiragana"]},   
  {kanji:"し", reading: "", meanings:["shi"], categories: ["hiragana"]},   
  {kanji:"す", reading: "", meanings:["su"], categories: ["hiragana"]},   
  {kanji:"せ", reading: "", meanings:["se"], categories: ["hiragana"]},   
  {kanji:"そ", reading: "", meanings:["so"], categories: ["hiragana"]},
  {kanji:"ざ", reading: "", meanings:["za"], categories: ["hiragana"]},
  {kanji:"じ", reading: "", meanings:["ji"], categories: ["hiragana"]},
  {kanji:"ず", reading: "", meanings:["zu"], categories: ["hiragana"]},
  {kanji:"ぜ", reading: "", meanings:["ze"], categories: ["hiragana"]},
  {kanji:"ぞ", reading: "", meanings:["zo"], categories: ["hiragana"]},
  {kanji:"た", reading: "", meanings:["ta"], categories: ["hiragana"]},   
  {kanji:"ち", reading: "", meanings:["chi"], categories: ["hiragana"]},   
  {kanji:"つ", reading: "", meanings:["tsu"], categories: ["hiragana"]},   
  {kanji:"て", reading: "", meanings:["te"], categories: ["hiragana"]},   
  {kanji:"と", reading: "", meanings:["to"], categories: ["hiragana"]},
  {kanji:"だ", reading: "", meanings:["da"], categories: ["hiragana"]},
  {kanji:"ぢ", reading: "", meanings:["ji"], categories: ["hiragana"]},
  {kanji:"づ", reading: "", meanings:["zu"], categories: ["hiragana"]},
  {kanji:"で", reading: "", meanings:["de"], categories: ["hiragana"]},
  {kanji:"ど", reading: "", meanings:["do"], categories: ["hiragana"]},
  {kanji:"な", reading: "", meanings:["na"], categories: ["hiragana"]},   
  {kanji:"に", reading: "", meanings:["ni"], categories: ["hiragana"]},   
  {kanji:"ぬ", reading: "", meanings:["nu"], categories: ["hiragana"]},   
  {kanji:"ね", reading: "", meanings:["ne"], categories: ["hiragana"]},   
  {kanji:"の", reading: "", meanings:["no"], categories: ["hiragana"]},
  {kanji:"は", reading: "", meanings:["ha"], categories: ["hiragana"]},   
  {kanji:"ひ", reading: "", meanings:["hi"], categories: ["hiragana"]},   
  {kanji:"ふ", reading: "", meanings:["fu"], categories: ["hiragana"]},   
  {kanji:"へ", reading: "", meanings:["he"], categories: ["hiragana"]},   
  {kanji:"ほ", reading: "", meanings:["ho"], categories: ["hiragana"]},
  {kanji:"ば", reading: "", meanings:["ba"], categories: ["hiragana"]},
  {kanji:"び", reading: "", meanings:["bi"], categories: ["hiragana"]},
  {kanji:"ぶ", reading: "", meanings:["bu"], categories: ["hiragana"]},
  {kanji:"べ", reading: "", meanings:["be"], categories: ["hiragana"]},
  {kanji:"ぼ", reading: "", meanings:["bo"], categories: ["hiragana"]},
  {kanji:"ぱ", reading: "", meanings:["pa"], categories: ["hiragana"]},
  {kanji:"ぴ", reading: "", meanings:["pi"], categories: ["hiragana"]},
  {kanji:"ぷ", reading: "", meanings:["pu"], categories: ["hiragana"]},
  {kanji:"ぺ", reading: "", meanings:["pe"], categories: ["hiragana"]},
  {kanji:"ぽ", reading: "", meanings:["po"], categories: ["hiragana"]},
  {kanji:"ま", reading: "", meanings:["ma"], categories: ["hiragana"]},   
  {kanji:"み", reading: "", meanings:["mi"], categories: ["hiragana"]},   
  {kanji:"む", reading: "", meanings:["mu"], categories: ["hiragana"]},   
  {kanji:"め", reading: "", meanings:["me"], categories: ["hiragana"]},   
  {kanji:"も", reading: "", meanings:["mo"], categories: ["hiragana"]},
  {kanji:"や", reading: "", meanings:["ya"], categories: ["hiragana"]},      
  {kanji:"ゆ", reading: "", meanings:["yu"], categories: ["hiragana"]},   
  {kanji:"よ", reading: "", meanings:["yo"], categories: ["hiragana"]},
  {kanji:"ら", reading: "", meanings:["ra"], categories: ["hiragana"]},   
  {kanji:"り", reading: "", meanings:["ri"], categories: ["hiragana"]},   
  {kanji:"る", reading: "", meanings:["ru"], categories: ["hiragana"]},   
  {kanji:"れ", reading: "", meanings:["re"], categories: ["hiragana"]},   
  {kanji:"ろ", reading: "", meanings:["ro"], categories: ["hiragana"]},
  {kanji:"わ", reading: "", meanings:["wa"], categories: ["hiragana"]},    
  {kanji:"を", reading: "", meanings:["o"], categories: ["hiragana"]},
  {kanji:"ん", reading: "", meanings:["n"], categories: ["hiragana"]},
  )

  //katakana
  answers.push(
  {kanji:"ア", reading: "", meanings:["a"], categories: ["katakana"]},   
  {kanji:"イ", reading: "", meanings:["i"], categories: ["katakana"]},   
  {kanji:"ウ", reading: "", meanings:["u"], categories: ["katakana"]},   
  {kanji:"エ", reading: "", meanings:["e"], categories: ["katakana"]},   
  {kanji:"オ", reading: "", meanings:["o"], categories: ["katakana"]},
  {kanji:"カ", reading: "", meanings:["ka"], categories: ["katakana"]},   
  {kanji:"キ", reading: "", meanings:["ki"], categories: ["katakana"]},   
  {kanji:"ク", reading: "", meanings:["ku"], categories: ["katakana"]},   
  {kanji:"ケ", reading: "", meanings:["ke"], categories: ["katakana"]},   
  {kanji:"コ", reading: "", meanings:["ko"], categories: ["katakana"]},
  {kanji:"ガ", reading: "", meanings:["ga"], categories: ["katakana"]},   
  {kanji:"ギ", reading: "", meanings:["gi"], categories: ["katakana"]},   
  {kanji:"グ", reading: "", meanings:["gu"], categories: ["katakana"]},   
  {kanji:"ゲ", reading: "", meanings:["ge"], categories: ["katakana"]},   
  {kanji:"ゴ", reading: "", meanings:["go"], categories: ["katakana"]},
  {kanji:"サ", reading: "", meanings:["sa"], categories: ["katakana"]},   
  {kanji:"シ", reading: "", meanings:["shi"], categories: ["katakana"]},   
  {kanji:"ス", reading: "", meanings:["su"], categories: ["katakana"]},   
  {kanji:"セ", reading: "", meanings:["se"], categories: ["katakana"]},   
  {kanji:"ソ", reading: "", meanings:["so"], categories: ["katakana"]},
  {kanji:"ザ", reading: "", meanings:["za"], categories: ["katakana"]},   
  {kanji:"ジ", reading: "", meanings:["ji"], categories: ["katakana"]},   
  {kanji:"ズ", reading: "", meanings:["zu"], categories: ["katakana"]},   
  {kanji:"ゼ", reading: "", meanings:["ze"], categories: ["katakana"]},   
  {kanji:"ゾ", reading: "", meanings:["zo"], categories: ["katakana"]},
  {kanji:"タ", reading: "", meanings:["ta"], categories: ["katakana"]},   
  {kanji:"チ", reading: "", meanings:["chi"], categories: ["katakana"]},   
  {kanji:"ツ", reading: "", meanings:["tsu"], categories: ["katakana"]},   
  {kanji:"テ", reading: "", meanings:["te"], categories: ["katakana"]},   
  {kanji:"ト", reading: "", meanings:["to"], categories: ["katakana"]},
  {kanji:"ダ", reading: "", meanings:["da"], categories: ["katakana"]},   
  {kanji:"ヂ", reading: "", meanings:["ji"], categories: ["katakana"]},   
  {kanji:"ヅ", reading: "", meanings:["zu"], categories: ["katakana"]},   
  {kanji:"デ", reading: "", meanings:["de"], categories: ["katakana"]},   
  {kanji:"ド", reading: "", meanings:["do"], categories: ["katakana"]},
  {kanji:"ナ", reading: "", meanings:["na"], categories: ["katakana"]},   
  {kanji:"ニ", reading: "", meanings:["ni"], categories: ["katakana"]},   
  {kanji:"ヌ", reading: "", meanings:["nu"], categories: ["katakana"]},   
  {kanji:"ネ", reading: "", meanings:["ne"], categories: ["katakana"]},   
  {kanji:"ノ", reading: "", meanings:["no"], categories: ["katakana"]},
  {kanji:"ハ", reading: "", meanings:["ha"], categories: ["katakana"]},   
  {kanji:"ヒ", reading: "", meanings:["hi"], categories: ["katakana"]},   
  {kanji:"フ", reading: "", meanings:["fu"], categories: ["katakana"]},   
  {kanji:"ヘ", reading: "", meanings:["he"], categories: ["katakana"]},   
  {kanji:"ホ", reading: "", meanings:["ho"], categories: ["katakana"]},
  {kanji:"バ", reading: "", meanings:["ba"], categories: ["katakana"]},   
  {kanji:"ビ", reading: "", meanings:["bi"], categories: ["katakana"]},   
  {kanji:"ブ", reading: "", meanings:["bu"], categories: ["katakana"]},   
  {kanji:"ベ", reading: "", meanings:["be"], categories: ["katakana"]},   
  {kanji:"ボ", reading: "", meanings:["bo"], categories: ["katakana"]},
  {kanji:"パ", reading: "", meanings:["pa"], categories: ["katakana"]},   
  {kanji:"ピ", reading: "", meanings:["pi"], categories: ["katakana"]},   
  {kanji:"プ", reading: "", meanings:["pu"], categories: ["katakana"]},   
  {kanji:"ペ", reading: "", meanings:["pe"], categories: ["katakana"]},   
  {kanji:"ポ", reading: "", meanings:["po"], categories: ["katakana"]},
  {kanji:"マ", reading: "", meanings:["ma"], categories: ["katakana"]},   
  {kanji:"ミ", reading: "", meanings:["mi"], categories: ["katakana"]},   
  {kanji:"ム", reading: "", meanings:["mu"], categories: ["katakana"]},   
  {kanji:"メ", reading: "", meanings:["me"], categories: ["katakana"]},   
  {kanji:"モ", reading: "", meanings:["mo"], categories: ["katakana"]},
  {kanji:"ヤ", reading: "", meanings:["ya"], categories: ["katakana"]},   
  {kanji:"ユ", reading: "", meanings:["yu"], categories: ["katakana"]},   
  {kanji:"ヨ", reading: "", meanings:["yo"], categories: ["katakana"]},
  {kanji:"ラ", reading: "", meanings:["ra"], categories: ["katakana"]},   
  {kanji:"リ", reading: "", meanings:["ri"], categories: ["katakana"]},   
  {kanji:"ル", reading: "", meanings:["ru"], categories: ["katakana"]},   
  {kanji:"レ", reading: "", meanings:["re"], categories: ["katakana"]},   
  {kanji:"ロ", reading: "", meanings:["ro"], categories: ["katakana"]},
  {kanji:"ワ", reading: "", meanings:["wa"], categories: ["katakana"]},
  {kanji:"ヲ", reading: "", meanings:["wo"], categories: ["katakana"]},
  {kanji:"ン", reading: "", meanings:["n"], categories: ["katakana"]},
  )

  //numbers
  answers.push(
  {kanji:"一", reading: "ichi", meanings:["1"], categories: ["numbers"]},
  {kanji:"二", reading: "ni", meanings:["2"], categories: ["numbers"]},
  {kanji:"三", reading: "san", meanings:["3"], categories: ["numbers"]},
  {kanji:"四", reading: "yo/yon", meanings:["4"], categories: ["numbers"]},
  {kanji:"五", reading: "go", meanings:["5"], categories: ["numbers"]},
  {kanji:"六", reading: "roku", meanings:["6"], categories: ["numbers"]},
  {kanji:"七", reading: "shichi/nana", meanings:["7"], categories: ["numbers"]},
  {kanji:"八", reading: "hachi", meanings:["8"], categories: ["numbers"]},
  {kanji:"九", reading: "ku/kyu", meanings:["9"], categories: ["numbers"]},
  {kanji:"十", reading: "jyu", meanings:["10"], categories: ["numbers"]},
  {kanji:"百", reading: "hyaku", meanings:["100"], categories: ["numbers"]},
  {kanji:"千", reading: "sen", meanings:["1000"], categories: ["numbers"]},
  )

  //days
  answers.push(
  {kanji:"土曜日",reading: "doyoubi", meanings:["saturday"], categories: ["days"]},
  {kanji:"日曜日",reading: "nichiyoubi", meanings:["sunday"], categories: ["days"]},
  )

  //random interesting ones
  answers.push(
  {kanji:"古い", reading: "furui",meanings: ["old"], categories: ["interesting"]},
  //{kanji:"大き", reading: "ooki",meanings: ["big"], categories: ["interesting"]},
  {kanji:"買います", reading: "kaimasu", meanings: ["buy"], categories: ["interesting"]},
  {kanji:"新しい", reading: "atarashi", meanings: ["new"], categories: ["interesting"]},
  {kanji:"小さい", reading: "chiisai", meanings: ["small"], categories: ["interesting"]},
  {kanji:"来ます", reading: "kimasu", meanings: ["come"], categories: ["interesting"]},
  {kanji:"時間", reading: "jikan", meanings: ["time"], categories: ["interesting"]},
  {kanji:"分ぐらい", reading: "fungurai", meanings: ["minute"], categories: ["interesting"]},
  {kanji:"好きです", reading: "sukidesu", meanings: ["like"], categories: ["interesting"]},
  {kanji:"問", reading: "mon/toi", meanings: ["questions", "question"], categories: ["interesting", "lastAdded"]},
  {kanji:"何", reading: "nan", meanings: ["what"], categories: ["interesting", "lastAdded"]},
  {kanji:"何時", reading: "nanji", meanings: ["when"], categories: ["interesting", "lastAdded"]},
  {kanji:"水", reading: "mizu", meanings: ["water"], categories: ["interesting", "lastAdded"]},
  {kanji:"食べます", reading: "tabemasu", meanings: ["eat"], categories: ["interesting", "lastAdded"]},
  {kanji:"高", reading: "takai", meanings: ["expensive"], categories: ["interesting", "lastAdded"]},
  {kanji:"少すこ", reading: "sukoshi", meanings: ["a bit"], categories: ["interesting", "lastAdded"]},
  )

  //mostUsed
  answers.push(
  {kanji:"日", reading: "hi", meanings: ["day"], categories: ["mostUsed"]},
  {kanji:"人", reading: "hito", meanings: ["person"], categories: ["mostUsed"]},
  //{kanji:"一", reading: "ichi", meanings: ["one"], categories: ["mostUsed"]},
  {kanji:"大", reading: "dai", meanings: ["big"], categories: ["mostUsed"]},
  {kanji:"年", reading: "nen", meanings: ["year"], categories: ["mostUsed"]},
  {kanji:"本", reading: "hon", meanings: ["book"], categories: ["mostUsed"]},
  {kanji:"中", reading: "chu", meanings: ["middle"], categories: ["mostUsed"]},
  {kanji:"出", reading: "deru", meanings: ["come out"], categories: ["mostUsed", "lastAdded"]},
  {kanji:"時", reading: "toki", meanings: ["time"], categories: ["mostUsed", "lastAdded"]},
  {kanji:"行", reading: "gyi", meanings: ["to go","row"], categories: ["mostUsed", "lastAdded"]},
  {kanji:"事", reading: "koto", meanings: ["matter","job"], categories: ["mostUsed", "lastAdded"]},
  //{kanji:"分", reading: "fun", meanings: ["minute"], categories: ["mostUsed", "lastAdded"]},
  {kanji:"会", reading: "kai", meanings: ["meeting"], categories: ["mostUsed", "lastAdded"]},
  {kanji:"上", reading: "ue", meanings: ["above","upper"], categories: ["mostUsed", "lastAdded"]},
  {kanji:"生", reading: "nama", meanings: ["raw","live"], categories: ["mostUsed", "lastAdded"]},
  {kanji:"国", reading: "kuni", meanings: ["land","large place"], categories: ["mostUsed", "lastAdded"]},
  )
  return answers;
}